"""
agents.py — Phase 2: the Planner agent, and ONLY the Planner.

Scope discipline (per EVALUATION_AND_ROADMAP.md's phase numbering): Coder,
Tester, and Reviewer get added to this file in Phase 4, alongside the graph
wiring that routes between them. Adding stub versions of them now would be
doing Phase 4's job early — see PHASE_0_1_PROGRESS_AND_DECISIONS.md's note
on why phase discipline matters here.
"""

from __future__ import annotations

import json
import re

from pydantic import ValidationError

import sandbox
from llm_client import LLMCallError, call_llm
from state import (
    AcceptanceCriterion,
    CodeArtifact,
    PerCriterionResult,
    ReviewVerdict,
    Spec,
    TaskItem,
)

_CODE_FENCE_RE = re.compile(r"^```(?:json)?\s*\n?(.*?)\n?```\s*$", re.DOTALL)


def _strip_code_fence(raw: str) -> str:
    """Every agent prompt already says "no markdown code fences", but that's
    an instruction, not an enforcement — and as of this pass, coder/tester
    no longer get Groq's response_format=json_object structural nudge
    either (see llm_client.py's _ROLES_WITHOUT_JSON_MODE for why: it was
    causing opaque, undebuggable rejections on large code payloads). This
    is the cheap defensive counterweight: if a response is wrapped in a
    ```json ... ``` or ``` ... ``` fence despite the instruction, strip it
    before attempting json.loads() rather than failing on a fence that a
    human would recognize as "obviously JSON, just decorated." A no-op on
    any response that isn't fenced (including every existing mock
    fixture), so this changes nothing about current passing behavior.
    """
    stripped = raw.strip()
    match = _CODE_FENCE_RE.match(stripped)
    return match.group(1).strip() if match else stripped


class PlannerOutputError(Exception):
    """Raised when the Planner's LLM output can't be turned into a valid
    Spec. Carries the raw response text and (when available) the structured
    Pydantic errors, so whatever calls run_planner has enough to show a
    human (Phase 3's approval gate) or eventually feed back to the LLM as a
    "here's what was wrong, try again" prompt (Phase 5).

    Phase 2 itself does NOT retry — RetryCounters.spec_approval_retries is a
    Phase 3 concern. Phase 2's job is only to prove this failure is caught
    cleanly and says something specific, not "something went wrong."
    """

    def __init__(self, message: str, raw_response: str, errors: list | None = None):
        super().__init__(message)
        self.raw_response = raw_response
        self.errors = errors or []


def _build_prompt(requirement: str) -> str:
    """The literal text that would be sent to the LLM in real mode (Phase 5).
    Written now, even though nothing calls Groq with it yet, so mock-mode
    testing exercises something realistic rather than an empty string.

    Note the explicit instruction NOT to include an "id" on each acceptance
    criterion: AcceptanceCriterion.id is generated by our own code after
    parsing (AC1, AC2, ... in list order) — see PHASE_0_1_PROGRESS_AND_DECISIONS.md,
    "Open questions from Phase 1 — all resolved", item 1. Letting the LLM
    invent ids risks duplicates or inconsistent formats across runs.

    Also note tasks reference criteria by 0-based INDEX into
    acceptance_criteria, not by id and not by text. The LLM can't know the
    id we're about to assign (we haven't assigned it yet when the LLM
    responds), and referencing by text is fragile (a one-character mismatch
    breaks the link). Index into the list it just produced is the only
    stable thing available at response time — run_planner() below resolves
    each index to the real generated id right after parsing.
    """
    return f"""You are the Planner agent in a multi-agent SDLC pipeline.

Given this plain-English software requirement, produce a JSON object with
EXACTLY these fields and nothing else:

  "requirement": the requirement, copied verbatim.

  "acceptance_criteria": a list of objects, each with ONLY a "text" field —
      one independently-checkable condition the final code must satisfy.
      Do NOT include an "id" field on these; ids are assigned by our code,
      not by you.

  "tasks": a list of objects, each with:
      "id"                 — a short stable string like "T1", "T2", ...
      "description"        — what this task implements.
      "addresses_criteria" — a list of 0-based INTEGER INDICES into the
                              acceptance_criteria list above (NOT ids, NOT
                              text) naming which criteria this task
                              addresses. Use [] for setup/scaffolding tasks
                              that don't map to any single criterion.

Output ONLY the JSON object — no prose, no markdown code fences.

Requirement: {requirement}
"""


def run_planner(
    run_id: str,
    requirement: str,
    *,
    mock_response: str | None = None,
) -> Spec:
    """
    Call the LLM as the Planner (mocked for now), parse its JSON response,
    and return a validated Spec.

    Raises PlannerOutputError — with the raw text attached — the moment
    anything about the response can't be trusted: invalid JSON, a
    criterion/task missing a required field, a task's addresses_criteria
    pointing at an index that doesn't exist, or the assembled Spec itself
    failing Pydantic validation (e.g. zero acceptance criteria). Failing
    loudly and specifically here is the entire point of Phase 1's schema
    work — see EVALUATION_AND_ROADMAP.md's Phase 2 "done when".
    """
    prompt = _build_prompt(requirement)
    try:
        raw = call_llm("planner", prompt, mock_response=mock_response)
    except LLMCallError as e:
        # A call-level failure (Groq rejected the request outright, e.g.
        # json_validate_failed) is the same category of "hasn't produced
        # something usable yet" as a content-level failure below — see
        # PHASE_4_PROGRESS_AND_DECISIONS.md decision #1. Reusing
        # PlannerOutputError here, not a new exception type, is what lets
        # the existing spec_approval_retries loop resample through it.
        raise PlannerOutputError(f"Planner call failed: {e}", "") from e

    try:
        payload = json.loads(_strip_code_fence(raw))
    except json.JSONDecodeError as e:
        raise PlannerOutputError(f"Planner response was not valid JSON: {e}", raw)

    if not isinstance(payload, dict):
        raise PlannerOutputError(
            f"Planner response was valid JSON but not a JSON object "
            f"(got {type(payload).__name__}).",
            raw,
        )

    # --- Acceptance criteria: assign ids ourselves, AC1, AC2, ... in order ---
    raw_criteria = payload.get("acceptance_criteria", [])
    try:
        criteria = [
            AcceptanceCriterion(id=f"AC{i + 1}", text=c["text"])
            for i, c in enumerate(raw_criteria)
        ]
    except (KeyError, TypeError) as e:
        raise PlannerOutputError(
            f"Planner's acceptance_criteria were malformed (missing 'text' "
            f"or not a list of objects): {e}",
            raw,
        )
    except ValidationError as e:
        raise PlannerOutputError(
            f"Planner's acceptance_criteria failed schema validation: {e}",
            raw,
            errors=e.errors(),
        )

    # --- Tasks: resolve each addresses_criteria index to the real id ---
    raw_tasks = payload.get("tasks", [])
    tasks: list[TaskItem] = []
    try:
        for t in raw_tasks:
            resolved_ids = []
            for idx in t.get("addresses_criteria", []):
                if not isinstance(idx, int) or isinstance(idx, bool) or not (0 <= idx < len(criteria)):
                    raise PlannerOutputError(
                        f"Task {t.get('id')!r} references criterion index "
                        f"{idx!r}, which is out of range for the "
                        f"{len(criteria)} acceptance criteria the Planner "
                        f"actually produced.",
                        raw,
                    )
                resolved_ids.append(criteria[idx].id)
            tasks.append(
                TaskItem(
                    id=t["id"],
                    description=t["description"],
                    addresses_criteria=resolved_ids,
                )
            )
    except (KeyError, TypeError) as e:
        raise PlannerOutputError(
            f"Planner's tasks were malformed (missing 'id'/'description' or "
            f"not a list of objects): {e}",
            raw,
        )
    except ValidationError as e:
        raise PlannerOutputError(
            f"Planner's tasks failed schema validation: {e}", raw, errors=e.errors()
        )

    try:
        spec = Spec(
            run_id=run_id,
            requirement=payload.get("requirement", requirement),
            acceptance_criteria=criteria,
            tasks=tasks,
        )
    except ValidationError as e:
        raise PlannerOutputError(
            f"Planner output built individually-valid pieces, but the "
            f"assembled Spec failed validation: {e}",
            raw,
            errors=e.errors(),
        )

    return spec


# ---------------------------------------------------------------------------
# Phase 4: Coder, stub Tester, Reviewer
# ---------------------------------------------------------------------------
#
# Scope-discipline note (supersedes the module docstring above, which was
# accurate for Phase 2 but is now stale): Coder, Tester, and Reviewer are
# added here, in Phase 4, exactly as EVALUATION_AND_ROADMAP.md planned. The
# Tester started as a STUB — see run_tester_stub()'s docstring for exactly
# what that means and doesn't mean, and what replaced it in Phase 6 below.
# Coder and Reviewer go through the same call_llm() mock/real switch
# run_planner() already uses; nothing about how they're called is
# special-cased.


class CoderOutputError(Exception):
    """Raised when the Coder's LLM output can't be turned into a list of
    valid CodeArtifacts. Same shape and reasoning as PlannerOutputError
    above — carries the raw response so a caller (coder_node in graph.py)
    has enough to log a specific reason and decide whether to retry,
    rather than a bare stack trace.
    """

    def __init__(self, message: str, raw_response: str, errors: list | None = None):
        super().__init__(message)
        self.raw_response = raw_response
        self.errors = errors or []


class ReviewerOutputError(Exception):
    """Raised when the Reviewer's LLM output can't be turned into a list of
    valid ReviewVerdicts, OR when it returns verdicts but skips a criterion
    the Tester actually reported a result for (see the check at the end of
    run_reviewer() below — this closes the "worth a runtime assertion" TODO
    state.py's ReviewVerdict docstring flagged back in Phase 1; doing it
    here in Phase 4, at the point verdicts are first produced, instead of
    deferring it to Phase 7's report).
    """

    def __init__(self, message: str, raw_response: str, errors: list | None = None):
        super().__init__(message)
        self.raw_response = raw_response
        self.errors = errors or []


def _python_syntax_error(content: str, filename: str = "<generated>") -> str | None:
    """Returns a human-readable SyntaxError message if `content` isn't
    valid Python source, or None if it compiles cleanly. Uses
    `compile(..., "exec")` as a pure STATIC parse check — zero execution,
    no sandbox needed, no risk from the content itself.

    Exists to catch a real failure mode found on a live Groq run (see
    PHASE_6_PROGRESS_AND_DECISIONS.md): a free-tier model can return
    STRUCTURALLY VALID JSON whose string content is still broken Python —
    specifically, double-escaped newlines (the JSON contains a literal
    backslash-backslash-n instead of backslash-n), which collapses an
    entire file onto one physical line. That passes every check that
    existed before this one — valid JSON, has 'filename'/'content',
    matches the Pydantic schema — and previously wasn't caught until the
    Tester's sandbox tried to import/run it, burning a full Tester+Reviewer
    LLM round-trip (and a chunk of the shared retry budget) on code that
    was never going to work. A zero-cost, zero-network compile() check
    catches it instantly instead, with a precise, actionable reason.
    """
    try:
        compile(content, filename, "exec")
    except SyntaxError as e:
        return f"{type(e).__name__}: {e.msg} (line {e.lineno}, col {e.offset})"
    return None


class TesterOutputError(Exception):
    """Phase 6: raised when the real Tester's LLM-generated test scripts
    can't be turned into a runnable set of per-criterion tests — invalid
    JSON, a missing 'tests' list, a test entry missing 'criterion_id'/
    'test_code', or a test missing for one of the Spec's acceptance
    criteria. Same shape as CoderOutputError/ReviewerOutputError, same
    reasoning: graph.py's tester_node catches this and resamples through
    the existing test_review_retries budget rather than crashing the run.

    Deliberately NOT raised for "the generated test ran and the criterion
    failed" — that's real, honest signal (a PerCriterionResult with
    passed=False), not an error. This exception is only for "the Tester
    itself didn't produce something we can execute at all."
    """

    def __init__(self, message: str, raw_response: str, errors: list | None = None):
        super().__init__(message)
        self.raw_response = raw_response
        self.errors = errors or []


def _build_coder_prompt(spec: Spec, previous_error: str | None = None) -> str:
    """The literal text that would be sent to the LLM in real mode (Phase 5).
    Mirrors _build_prompt() above: written now so mock-mode testing
    exercises something realistic, even though nothing calls Groq with it
    yet.

    `previous_error` closes the "paste the bad response back to the LLM"
    gap PlannerOutputError's docstring flagged as a Phase 5 TODO back in
    Phase 2. Without it, every retry re-sent this EXACT prompt, so a model
    that made a systematic mistake (e.g. double-escaping newlines) had no
    way to learn it happened and kept repeating the identical mistake for
    the whole retry budget — the literal failure mode that burned all 5
    attempts on a live ShoppingCart run (4x invalid-JSON, then the same
    double-escaped-newline syntax error on the 5th). When set, this is
    str(exc) from the CoderOutputError the previous attempt raised, and is
    appended as a correction the model is explicitly told to fix.
    """
    criteria_desc = "\n".join(f"  - {c.id}: {c.text}" for c in spec.acceptance_criteria)
    tasks_desc = "\n".join(
        f"  - {t.id}: {t.description} (addresses: {', '.join(t.addresses_criteria) or 'none'})"
        for t in spec.tasks
    ) or "  (none given)"

    prompt = f"""You are the Coder agent in a multi-agent SDLC pipeline.

Given this approved spec, produce a JSON object with EXACTLY one field:

  "artifacts": a list of objects, each with:
      "filename" — a bare filename (no path separators — rejected by the
                    schema if present).
      "content"  — the full file content implementing the task(s) below,
                    as REAL, RUNNABLE Python source.
      "task_id"  — which task (by id, e.g. "T1") this file implements.

CRITICAL JSON-ESCAPING RULE for "content": encode it as an ORDINARY JSON
string, nothing more. A newline in your Python code must appear as
EXACTLY ONE backslash followed by the letter n (\n) inside the JSON
string — do NOT escape the backslash itself. Do not pre-escape the code
as if you were embedding a Python string literal inside another string.
If you find yourself writing two backslashes before an n, that is wrong
and will produce a file that collapses onto a single line and fails to
import.

Prefer ONE consolidated file for a single cohesive class/module, even if
multiple tasks address it, rather than splitting one small piece of
functionality across several separate files.

Output ONLY the JSON object — no prose, no markdown code fences.

Requirement: {spec.requirement}

Acceptance criteria:
{criteria_desc}

Tasks:
{tasks_desc}
"""

    if previous_error:
        prompt += f"""
THIS IS A RETRY. Your previous attempt failed for this exact reason:

{previous_error}

Fix that specific problem before answering again -- do not repeat it. If
it mentions JSON or a syntax error, re-read the CRITICAL JSON-ESCAPING
RULE above: a newline inside "content" must be a single backslash
followed by "n", never two backslashes followed by "n".
"""

    return prompt


def run_coder(
    run_id: str,
    spec: Spec,
    *,
    mock_response: str | None = None,
    previous_error: str | None = None,
) -> list[CodeArtifact]:
    """
    Call the LLM as the Coder (mocked for now), parse its JSON response, and
    return a validated list of CodeArtifacts.

    Raises CoderOutputError — with the raw text attached — for invalid
    JSON, a missing/malformed 'artifacts' list, an artifact missing
    'filename'/'content', or zero artifacts produced (nothing to test is
    treated as a Coder failure, not silently handed to the Tester as an
    empty run).

    `run_id` isn't used yet (Phase 4 doesn't persist CodeArtifacts to disk
    the way Phase 2 persists Specs) — kept in the signature now so it
    doesn't have to change shape later if Phase 6/7 want per-run artifact
    filenames, same reasoning llm_client.py already applies to `prompt`.

    `previous_error` is passed straight through to `_build_coder_prompt()`
    — see its docstring for why this exists. graph.py's coder_node is
    responsible for remembering the last CoderOutputError across retries
    and passing it back in here; run_coder() itself is stateless per call.
    """
    prompt = _build_coder_prompt(spec, previous_error=previous_error)
    try:
        raw = call_llm("coder", prompt, mock_response=mock_response)
    except LLMCallError as e:
        # Same reasoning as run_planner() above: a call-level failure
        # reuses CoderOutputError / test_review_retries rather than
        # crashing the run or inventing a new retry budget.
        raise CoderOutputError(f"Coder call failed: {e}", "") from e

    try:
        payload = json.loads(_strip_code_fence(raw))
    except json.JSONDecodeError as e:
        raise CoderOutputError(f"Coder response was not valid JSON: {e}", raw)

    if not isinstance(payload, dict) or not isinstance(payload.get("artifacts"), list):
        raise CoderOutputError(
            "Coder response was valid JSON but missing an 'artifacts' list.",
            raw,
        )

    raw_artifacts = payload["artifacts"]
    if not raw_artifacts:
        raise CoderOutputError("Coder produced zero artifacts — nothing to test.", raw)

    artifacts: list[CodeArtifact] = []
    try:
        for a in raw_artifacts:
            artifacts.append(
                CodeArtifact(
                    filename=a["filename"],
                    content=a["content"],
                    task_id=a.get("task_id"),
                )
            )
    except (KeyError, TypeError) as e:
        raise CoderOutputError(
            f"Coder's artifacts were malformed (missing 'filename'/'content' "
            f"or not a list of objects): {e}",
            raw,
        )
    except ValidationError as e:
        raise CoderOutputError(
            f"Coder's artifacts failed schema validation: {e}", raw, errors=e.errors()
        )

    # Catch broken-but-technically-valid-JSON content (e.g. double-escaped
    # newlines) HERE, before it ever reaches the Tester's sandbox — see
    # _python_syntax_error()'s docstring for the real run that surfaced
    # this. Cheaper (no LLM calls spent generating tests for code that
    # can't even be imported) and more honest (the error names the exact
    # syntax problem instead of every criterion failing with an opaque
    # import traceback).
    for artifact in artifacts:
        syntax_error = _python_syntax_error(artifact.content, artifact.filename)
        if syntax_error is not None:
            raise CoderOutputError(
                f"Coder's artifact {artifact.filename!r} is not valid Python "
                f"(caught before reaching the sandbox): {syntax_error}. A common "
                f"cause: the model double-escaped newlines in its JSON string "
                f"(wrote two backslashes before 'n' instead of one), which "
                f"collapses the whole file onto a single line.",
                raw,
            )

    return artifacts


def run_tester_stub(
    spec: Spec,
    code_artifacts: list[CodeArtifact],
    *,
    force_fail_criteria: list[str] | None = None,
) -> list[PerCriterionResult]:
    """
    Phase 4's STUB Tester. Kept in Phase 6 ONLY as the deliberate-override
    testing/demo hook (`force_fail_criteria`) — see this module's
    run_tester_real() below for the real sandboxed execution that
    production runs actually use. graph.py's tester_node calls THIS
    function only when the graph state explicitly carries
    force_tester_fail_criteria/force_tester_fail_attempts (test/demo
    runs), and calls run_tester_real() otherwise. A real Tester can't
    honestly "force" a criterion to fail regardless of whether the code
    actually satisfies it — that would contradict the entire point of
    Phase 6 — so the override intentionally keeps living on the
    honest-about-being-fake stub, never on the real path.

    No subprocess, no sandbox, no actually running the generated code.
    Rule-based logic, in order:
      1. If no code_artifacts were produced at all, every criterion fails
         with that as the explicit reason. This is the one part of this
         function that's a REAL rule, not a stub — "no code exists" is
         something we can honestly determine without executing anything.
      2. If a criterion's id is in `force_fail_criteria`, it fails with a
         detail that says so explicitly. This is a test/demo hook only.
      3. Otherwise, the criterion is assumed to pass. This is the actual
         "stub" part — there's no way to honestly know without execution.

    Every PerCriterionResult.detail is prefixed "[stub]" except the
    no-code-produced case, so nothing downstream (the Reviewer's prompt,
    Phase 7's traceability report) can mistake a stub result for a real
    one.
    """
    force_fail = set(force_fail_criteria or [])
    results: list[PerCriterionResult] = []

    for criterion in spec.acceptance_criteria:
        if not code_artifacts:
            results.append(
                PerCriterionResult(
                    criterion_id=criterion.id,
                    passed=False,
                    detail="No code artifacts were produced to test.",
                )
            )
        elif criterion.id in force_fail:
            results.append(
                PerCriterionResult(
                    criterion_id=criterion.id,
                    passed=False,
                    detail=(
                        f"[stub] forced failure for {criterion.id} "
                        f"(test/demo hook only — production runs use "
                        f"run_tester_real(), Phase 6)."
                    ),
                )
            )
        else:
            results.append(
                PerCriterionResult(
                    criterion_id=criterion.id,
                    passed=True,
                    detail="[stub] assumed pass — test/demo hook only, not real execution.",
                )
            )

    return results


# ---------------------------------------------------------------------------
# Phase 6: real Tester — sandboxed, per-criterion execution
# ---------------------------------------------------------------------------
#
# DECISION: the Tester generates its OWN test code via the worker LLM (the
# same "mechanical, high-volume, smaller model" tier the Coder uses per
# PROJECT_BRIEF.md's mixed-model decision), one self-contained script per
# acceptance criterion, which is then genuinely executed in sandbox.py's
# subprocess sandbox. This was the one real architectural gap the roadmap
# didn't spell out explicitly: "check/derive a result per acceptance
# criterion" requires SOMETHING to execute, and nothing upstream (the
# Coder) produces test code today — only implementation code. Generating
# the test per-criterion, right before running it, is what makes "one
# result per criterion" honest rather than a single script's exit code
# fanned out across N criteria.
#
# This also matches the SAME reliability lesson Phase 5 already learned
# with the Planner/Coder/Reviewer: structured JSON output, validated with
# Pydantic-adjacent manual checks below, not the LLM directly executing
# anything or being trusted blind.


def _build_tester_prompt(spec: Spec, code_artifacts: list[CodeArtifact]) -> str:
    """Includes the FULL content of every code artifact (not just
    filenames) — the Tester LLM has to reference real function/class names
    to write a test that actually exercises the code, the same reason
    run_coder()'s prompt includes the full spec rather than a summary.
    """
    criteria_desc = "\n".join(f"  - {c.id}: {c.text}" for c in spec.acceptance_criteria)
    files_desc = "\n\n".join(
        f"--- {a.filename} ---\n{a.content}" for a in code_artifacts
    )
    module_names = ", ".join(a.filename.removesuffix(".py") for a in code_artifacts)

    return f"""You are the Tester agent in a multi-agent SDLC pipeline. You do
NOT judge correctness yourself — you write a small Python test SCRIPT per
acceptance criterion, which will actually be executed in a sandbox. The
exit code decides pass/fail, not your opinion.

Produce a JSON object with EXACTLY one field:

  "tests": a list of objects, ONE PER ACCEPTANCE CRITERION LISTED BELOW
      (same criterion_id values, none missing, none invented), each with:
      "criterion_id" — matching one of the criterion ids below.
      "test_code"    — a COMPLETE, SELF-CONTAINED Python script (no
                        markdown fences) that:
                          - imports what it needs from these modules by
                            name: {module_names}
                          - exercises the code against this ONE criterion
                          - lets an AssertionError (or any uncaught
                            exception) propagate if the criterion is NOT
                            satisfied — do not catch and swallow it
                          - exits normally (falls off the end) if the
                            criterion IS satisfied
                          - uses ONLY the Python standard library, no
                            network access, no reading stdin, no pytest
                            (this is a plain script run directly, not
                            collected by a test runner)

CRITICAL JSON-ESCAPING RULE for "test_code": encode it as an ORDINARY
JSON string, nothing more. A newline in your script must appear as
EXACTLY ONE backslash followed by the letter n (\n) inside the JSON
string — do NOT escape the backslash itself. Do not pre-escape the code
as if you were embedding a Python string literal inside another string.
Two backslashes before an n will produce a script that collapses onto a
single line and fails to even run.

Output ONLY the JSON object — no prose, no markdown code fences.

Acceptance criteria:
{criteria_desc}

Code under test:
{files_desc}
"""


def run_tester_real(
    run_id: str,
    spec: Spec,
    code_artifacts: list[CodeArtifact],
    *,
    mock_response: str | None = None,
) -> list[PerCriterionResult]:
    """
    Phase 6's real Tester. For each acceptance criterion: ask the worker
    LLM for a standalone test script (see _build_tester_prompt), write it
    alongside the Coder's actual code artifacts into a fresh sandbox
    directory (sandbox.run_sandboxed — a NEW temp dir per criterion, so
    one test can't see or be influenced by another), execute it for real,
    and derive passed/failed from the real exit code plus captured
    stdout/stderr — never a guess, never an LLM opinion standing in for
    execution.

    Raises TesterOutputError (not a PerCriterionResult failure) when the
    Tester LLM itself doesn't produce usable test code — invalid JSON, a
    missing 'tests' list, a malformed entry, or a missing criterion_id.
    That's a "the Tester hasn't produced something usable yet" failure,
    same category Phase 4's decision #1 established for Planner/Coder,
    and graph.py's tester_node resamples through test_review_retries
    exactly like a CoderOutputError today.

    `run_id` is accepted but unused for the same forward-compatibility
    reason run_coder() already documents — kept in case Phase 7's report
    or future persistence wants per-run test-artifact filenames.
    """
    if not code_artifacts:
        # Same honest, non-LLM rule run_tester_stub() applies: no code
        # means every criterion fails, and there's nothing to ask the
        # Tester LLM to write a test against.
        return [
            PerCriterionResult(
                criterion_id=c.id,
                passed=False,
                detail="No code artifacts were produced to test.",
            )
            for c in spec.acceptance_criteria
        ]

    prompt = _build_tester_prompt(spec, code_artifacts)
    try:
        raw = call_llm("tester", prompt, mock_response=mock_response)
    except LLMCallError as e:
        raise TesterOutputError(f"Tester call failed: {e}", "") from e

    try:
        payload = json.loads(_strip_code_fence(raw))
    except json.JSONDecodeError as e:
        raise TesterOutputError(f"Tester response was not valid JSON: {e}", raw)

    if not isinstance(payload, dict) or not isinstance(payload.get("tests"), list):
        raise TesterOutputError(
            "Tester response was valid JSON but missing a 'tests' list.", raw
        )

    tests_by_id: dict[str, str] = {}
    try:
        for t in payload["tests"]:
            tests_by_id[t["criterion_id"]] = t["test_code"]
    except (KeyError, TypeError) as e:
        raise TesterOutputError(
            f"Tester's tests were malformed (missing 'criterion_id'/"
            f"'test_code' or not a list of objects): {e}",
            raw,
        )

    expected_ids = {c.id for c in spec.acceptance_criteria}
    missing = expected_ids - tests_by_id.keys()
    if missing:
        raise TesterOutputError(
            f"Tester did not produce a test for every acceptance criterion "
            f"(missing: {sorted(missing)}).",
            raw,
        )

    # Same static syntax pre-check run_coder() now applies to CodeArtifacts
    # — see _python_syntax_error()'s docstring. Deliberately raised as
    # TesterOutputError (the Tester's own bug) rather than a
    # PerCriterionResult failure: a test script that doesn't even parse
    # would otherwise be reported as "the CODE failed this criterion" when
    # the actual defect is in the Tester's generated test, not the Coder's
    # implementation — an important distinction for anyone reading the
    # traceability report and trying to decide what to fix.
    for criterion_id, test_code in tests_by_id.items():
        syntax_error = _python_syntax_error(test_code, f"test_{criterion_id}.py")
        if syntax_error is not None:
            raise TesterOutputError(
                f"Tester's generated test for {criterion_id} is not valid "
                f"Python (caught before executing it in the sandbox): "
                f"{syntax_error}. This is a defect in the Tester's own "
                f"generated test, not necessarily in the code under test.",
                raw,
            )

    code_files = {a.filename: a.content for a in code_artifacts}

    results: list[PerCriterionResult] = []
    for criterion in spec.acceptance_criteria:
        test_filename = f"test_{criterion.id}.py"
        files_for_this_run = {**code_files, test_filename: tests_by_id[criterion.id]}
        outcome = sandbox.run_sandboxed(files_for_this_run, entry_file=test_filename)
        passed = outcome.returncode == 0 and not outcome.timed_out

        if passed:
            detail = "PASS (real sandboxed execution, exit 0)."
            if outcome.stdout.strip():
                detail += f" stdout: {outcome.stdout.strip()[:300]}"
        else:
            reason = (
                outcome.stderr.strip()
                or outcome.stdout.strip()
                or f"nonzero exit code {outcome.returncode}"
            )
            detail = f"FAILED (real sandboxed execution): {reason[:800]}"

        results.append(
            PerCriterionResult(criterion_id=criterion.id, passed=passed, detail=detail)
        )

    return results


def _build_reviewer_prompt(spec: Spec, test_results: list[PerCriterionResult]) -> str:
    """Mirrors _build_prompt() / _build_coder_prompt() above. Only ever sent
    in real mode (Phase 5) — in Phase 4's mock mode, call_llm() ignores it
    entirely, same as every other agent's prompt right now.
    """
    criteria_by_id = {c.id: c.text for c in spec.acceptance_criteria}
    lines = []
    for r in test_results:
        crit_text = criteria_by_id.get(r.criterion_id, "(unknown criterion)")
        verdict = "PASSED" if r.passed else "FAILED"
        lines.append(f"  - {r.criterion_id} ({crit_text}): {verdict} — {r.detail}")
    results_desc = "\n".join(lines) or "  (no test results)"

    return f"""You are the Reviewer agent in a multi-agent SDLC pipeline.

Given the test results below, produce a JSON object with EXACTLY one field:

  "verdicts": a list of objects, one per criterion, each with:
      "criterion_id"  — matching one of the criterion ids below.
      "approved"      — true/false: your judgment on whether this criterion
                         is genuinely satisfied.
      "justification" — a short, specific reason referencing the test result.

Return exactly one verdict for every criterion_id listed below — do not
omit any, and do not invent new ones.

Output ONLY the JSON object — no prose, no markdown code fences.

Test results:
{results_desc}
"""


def run_reviewer(
    run_id: str,
    spec: Spec,
    test_results: list[PerCriterionResult],
    *,
    mock_response: str | None = None,
) -> list[ReviewVerdict]:
    """
    Call the LLM as the Reviewer (mocked for now), parse its JSON response,
    and return a validated list of ReviewVerdicts.

    Raises ReviewerOutputError for invalid JSON, a missing/malformed
    'verdicts' list, a verdict missing a required field, OR a verdict list
    missing an entry for a criterion the Tester reported on.

    Phase 5 update: the default canned mock "reviewer" response now reads
    as prompt-responsive in real mode (see PHASE_5_PROGRESS_AND_DECISIONS.md's
    "Key finding") — with Phase 6's real Tester now supplying real
    execution evidence instead of stub results, a real-mode Reviewer has
    genuine test evidence to approve or reject against for the first time.
    """
    prompt = _build_reviewer_prompt(spec, test_results)
    try:
        raw = call_llm("reviewer", prompt, mock_response=mock_response)
    except LLMCallError as e:
        # Same reasoning as run_planner()/run_coder() above.
        raise ReviewerOutputError(f"Reviewer call failed: {e}", "") from e

    try:
        payload = json.loads(_strip_code_fence(raw))
    except json.JSONDecodeError as e:
        raise ReviewerOutputError(f"Reviewer response was not valid JSON: {e}", raw)

    if not isinstance(payload, dict) or not isinstance(payload.get("verdicts"), list):
        raise ReviewerOutputError(
            "Reviewer response was valid JSON but missing a 'verdicts' list.",
            raw,
        )

    verdicts: list[ReviewVerdict] = []
    try:
        for v in payload["verdicts"]:
            verdicts.append(
                ReviewVerdict(
                    criterion_id=v["criterion_id"],
                    approved=v["approved"],
                    justification=v["justification"],
                )
            )
    except (KeyError, TypeError) as e:
        raise ReviewerOutputError(
            f"Reviewer's verdicts were malformed (missing a required field "
            f"or not a list of objects): {e}",
            raw,
        )
    except ValidationError as e:
        raise ReviewerOutputError(
            f"Reviewer's verdicts failed schema validation: {e}", raw, errors=e.errors()
        )

    tested_ids = {r.criterion_id for r in test_results}
    verdict_ids = {v.criterion_id for v in verdicts}
    missing = tested_ids - verdict_ids
    if missing:
        raise ReviewerOutputError(
            f"Reviewer did not return a verdict for every tested criterion "
            f"(missing: {sorted(missing)}).",
            raw,
        )

    return verdicts
